name: CoinHiveMCPlugin
main: io.github.kuohsuanlo.coinhivemc.CoinHiveMCPlugin
version: ${version}
softdepend: [GriefPrevention]
softdepend: [PlaceholderAPI]
commands:
  coinhivemc:
    description: .
    usage: 
permissions:
    coinhivemc.reload:
        description: player with this node could reload the plugin's config.
        default: op
    coinhivemc.list:
        description: player with this node could list all players info by text output.
        default: op
    coinhivemc.withdraw:
        description: player with this node could withdraw players balance.
        default: op
    coinhivemc.exchange:
        description: player with this node could exchange items with balance.
        default: op
    coinhivemc.free-exchange:
        description: player with this node could exchange items free.
        default: op
    coinhivemc.exempt.fee:
        description: player with this node could exchange with 1 Hash.
        default: op
    coinhivemc.exempt.place:
        description: player with this node could exchange at any where.
        default: op
        
        